### ISSUE TITLE
Table of Contents "Introduction" links to incorrect page

### ISSUE THREAD

**Issue by smart-alek** [Bradfield/algos#37]
Clicking on the "Introduction" link takes you to http://bradfield.institute instead of http://bradfield.institute/algos/analysis/introduction/.

**Comment by ozan** [comment]
This one should point to http://bradfield.institute/algos/ as it's the introduction to the book itself. In any case, fixed above, thanks for catching!

**Comment by smart-alek** [comment]
My bad, that's the URL I meant to copy/paste. Curse my clipboard! :clipboard: And thanks for taking care of it!
