### ISSUE TITLE
decimal-to-binary.png image is inaccurate

### ISSUE THREAD

**Issue by MaxDavila** [Bradfield/algos#61]
The `push remainder` `pop remainder` arrows, or text depending on how you see it, are inverted. The `push remainder` arrow should be pointing towards the base of the stack not the other way around. 

https://github.com/Bradfield/algos/blob/master/book/stacks/figures/decimal-to-binary.png

**Comment by ozan** [comment]
Thanks Max! I can see your confusion. I believe the original creators of the image (in the book that we forked for this) were trying to indicate the direction that the stack would grow or shrink, as opposed to the movement of the items themselves. If we decide to redo the images at some point, we might switch it to be the other way around.
