### ISSUE TITLE
The issue for Shortest Path with Dijkstra’s Algorithm

### ISSUE THREAD

**Issue by LennyFan** [Bradfield/algos#67]
Thanks for sharing this amazing work.

I feel like the algorithm in  Shortest Path with Dijkstra’s Algorithm is not correct.
Since heapq won't update(sort) automatically after you update the value. 

For example, 
if I rename 'Z' to be 'A', it will first pop 'X' and then pop 'Z'. However, the distance to Z now is infinite. In this case it will work, but if we add another node 'B" which the shortest path from 'X' to 'B' is 'X' -> 'Z' -> 'B', then this algorithm won't work out. 

```
example_graph = {
    'B': {'A': 9},
    'U': {'V': 2, 'W': 5, 'X': 1},
    'V': {'U': 2, 'X': 2, 'W': 3},
    'W': {'V': 3, 'U': 5, 'X': 3, 'Y': 1, 'A': 5},
    'X': {'U': 1, 'V': 2, 'W': 3, 'Y': 1},
    'Y': {'X': 1, 'W': 1, 'A': 1},
    'A': {'W': 5, 'Y': 1, 'B':9}
}
# calculate_distances(example_graph, 'X')
# => {'A': 2, 'B': inf, 'U': 1, 'V': 2, 'W': 2, 'X': 0, 'Y': 1}
```

**Comment by ozan** [comment]
Hi, thank you for catching this! If you're comfortable with Python, would you like to add a test case and fix? We'd be very grateful :)
